### ISSUE TITLE
Cannot Start Stacksync Server

### ISSUE THREAD

**Issue by 2XL** [stacksync/sync-service#12]
```
xxx@stacksync:/var/log$ sudo service stacksync-server start
Starting StackSync Server...
StackSync Server could not start.
xxx@stacksync:/var/log$ 
```

 the following error apears: 

> [2016-05-23 18:02:52] ERROR SyncServiceDaemon:116 - Could not initialize ObjectMQ.  
> java.net.ConnectException: Connection refused
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:579)
> 	at com.rabbitmq.client.ConnectionFactory.createFrameHandler(ConnectionFactory.java:445)
> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:504)
> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:533)
> 	at omq.common.util.OmqConnectionFactory.getNewConnection(OmqConnectionFactory.java:105)
> 	at omq.common.broker.Broker.<init>(Broker.java:62)
> 	at com.stacksync.syncservice.SyncServiceDaemon.init(SyncServiceDaemon.java:112)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:207)
> Service exit with a return value of 5

**Comment by 2XL** [comment]
closed, my rabbit mq server port was switched
